#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xmodmap ~/.Xmodmap;

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh

bspc config border_width       3
bspc config window_gap         4
bspc config focused_border_color "#ff4949"
bspc config split_ratio          0.5
bspc config gapless_monocle      true

bspc rule -a Matplotlib state=floating -o rectangle=720x720+600+220
xset r rate 175 50 # reducir delay de teclas
setxkbmap -option caps:swapescape
bspc wm -O HDMI1 eDP1

xrandr --output eDP1 --auto --output HDMI1 --auto --above eDP1

feh --bg-fill ~/media/Pictures/bosque_sur.jpg ~/media/Pictures/bb_chasco.png

startup_apps.sh
