#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xmodmap ~/.Xmodmap;

xsetroot -cursor_name left_ptr &

#pkill -USR1 -x sxhkd

# picom &

$HOME/.config/polybar/launch.sh
# /etc/polybar/launch.sh

#spotify &
#wmctrl -r Spotify -t 7
#bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"

bspc config border_width       3
bspc config window_gap         4
#bspc config focused_border_color "#65af91"
#bspc config focused_border_color "#ff8787"
bspc config focused_border_color "#ff4949"
bspc config split_ratio          0.52
bspc config split_type horizontal # no funciona :(
#bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Matplotlib state=floating -o rectangle=720x720+600+220
#bspc rule -a sxiv state=floating
#bspc rule -a Anki desktop='^6' follow=off focus=off
#bspc rule -a spotify desktop='^9' follow=off focus=off
#bspc rule -a Zathura state=tiled
#bspc rule -a praat-open-files split_type=vertical

#xrandr --output eDP1 --scale 0.8x0.8
#xrandr --output DP1 --scale 1x1.20


xset r rate 175 50 # reducir delay de teclas
setxkbmap -option caps:swapescape



#que workspaces quiero en cada monitor

#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

bspc wm -O HDMI1 eDP1

xrandr --output eDP1 --auto --output HDMI1 --auto --above eDP1

#feh --bg-fill ~/media/Pictures/bosque_sur.jpg
#feh --bg-fill ~/media/Pictures/bosque_sur.jpg /home/tdu/media/Pictures/feh_044577_000001_IMG_20220813_132331.jpg
feh --bg-fill ~/media/Pictures/bosque_sur.jpg ~/media/Pictures/bb_chasco.png

# bspc desktop -f 9 && st -e nvim /home/ttdduu/calendario.wiki
startup_apps.sh
